### ISSUE TITLE
"Does Not Exist" verification/validation rule in a Coded UI test doesn't work as expected

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#144]
The "Does Not Exist" verification/validation rule in a Coded UI test doesn't work as expected.

For example, there's a commented out validation rule check in `.\src\SpecBind.CodedUI.IntegrationTests\Features\ValidationFeatures.feature`:
```
#| Foo          | Does Not Exist |       | --> this may still need some work.
```

Why is it commented out?
Uncommenting it still makes the test pass.

In either case, I've found two issues:
1. If the row is set to 
```
| Foo          | Does Not Exist | true  |
````
Then the test still passes, but setting the row to:
```
| Foo          | Does Not Exist | false |
````
Will cause the test to fail.
This behavior isn't documented in the wiki.
What do the different field values (true, false, and empty) for the `Does Not Exist` validation rule imply?

2. Changing that row to
```
| Foo1          | Does Not Exist |       |
```
Will still cause the test to pass even though the `Foo1` property isn't defined in the `CreateCoursePage` model.
In this case, I expected the following exception:
```
SpecBind.Pages.ElementExecuteException: Could not locate property 'foo1' on page CreateCoursePage. Available Fields: 
Department
Description
Number
Popular
CourseTitle
Foo
```

Thank you.

**Comment by dpiessens** [comment]
Can't speak to why it was initially commented out, my guess is that I was having issues with the wait routine and I never enabled it after resolving the issue.

I never tested Does Not Exist in true/false states because I always assumed the state would be true given that I have an Exists qualifier. However, the logic does treat true/false as a value here and parse it. I would propose removing that evaluation it so it remains blank.

The logic in ValidateItemAction treats DoesNotExist as a special case and ignores the missing property. Based on the way you describe it above, I would agree that it should not treat a missing property as an allowed case.

A friendly general note, this is an open source project so documentation is more of a guide than a complete functional reference.
