### ISSUE TITLE
Specbind remotedriver? 

### ISSUE THREAD

**Issue by Gavey23** [dpiessens/specbind#73]
Hello, 

I know that specbind is capable of using the remote driver, please could you give me a direction as to where to get this working? I have followed the information given on the configuration page but am unable to get this working, and is erroring with 'remoteUrl is unrecognized and cold be due to the capitals. By giving a bit of direction that would be perfect, or put me into the right direction to see the source code with this. I am aiming to get this in the app.config as I know how to get this working with an Iwebdriver. 

Thanks

**Comment by dpiessens** [comment]
Hi,

The code for the remote driver is located here: https://github.com/dpiessens/specbind/blob/master/src/SpecBind.Selenium/SeleniumBrowserFactory.cs I believe the setting should be 'RemoteUrl' This feature isn't heavily used so there could be some issues.

**Comment by Gavey23** [comment]
Hello @dpiessens I have now resolved the issue, however I have encountered a smaller issue, I need to set up multiple browser settings and the way I believe I should od this is running a custom step which will allow me to change the app.config. Would you know how i could go about doing this? or a better way? 

Thanks.

**Comment by dpiessens** [comment]
Could you post an example of the settings you're trying to change? Just show app config examples of configuring for say Chrome and another for FireFox or IE. We might be able to do this with a setting convention for remote drivers.

**Comment by NickMcG** [comment]
I use SlowCheetah for this. SlowCheetah allows you to apply configuration transforms to App.config files, similar to how Visual Studio will natively apply configuration transforms to Web.config files.

For example, I have an App.config file that specifies most of the settings and defaults to Chrome for the browser. I will also set up Firefox and IE build configurations, and create a App.Firefox.config and App.IE.config configuration transform files with SlowCheetah. I put config transforms in those files to change the browser (App.Firefox.config will change the browser to Firefox, for example).

If I build with the default configuration (Debug or Release), it will run with the default settings (Chrome as the browser); otherwise, if I build with the Firefox configuration, it will run with Firefox as the browser. If you are using a build server, you should be able to configure the build server to run the tests with all of the build configurations (so you test all of the browsers).

One downside to this is that you can end up with a bunch of configuration files. For example, my current project has 3 environments (Development, QA/Staging, and Production) and 6 supported browsers (IE8-11, Chrome, and Firefox), which means I have 18 configuration files or transforms. I did do some experimentation with creating a composite browser (see issue #89). I got it working, but it is nothing I would want to merge back.

I hope that helps! Let me know if you want any clarifications.

**Comment by icnocop** [comment]
The ability to dynamically set the browser in a step definition has been added in pull request #151.
Also see #89.

**Comment by dpiessens** [comment]
Remote drivers have fallen out of favor with the various platforms so I'm closing this.
